import { Router } from 'express';
import { protect } from '../middlewares/auth.middleware';
import { restrictTo } from '../middlewares/rbac.middleware';
import { enterpriseController } from '../controllers/enterprise.controller';
import { validate } from '../middlewares/validate.middleware';
import { createOidcProviderSchema } from '../validations/enterprise.validation';

const router = Router();
router.use(protect, restrictTo('ADMIN'));
router.get('/operational-policy', enterpriseController.getOperationalPolicy);
router.put('/operational-policy', enterpriseController.updateOperationalPolicy);
router.get('/operational-readiness', enterpriseController.operationalReadiness);
router.get('/slo', enterpriseController.sloReport);
router.get('/recovery-evidence', enterpriseController.listRecoveryEvidence);
router.post('/recovery-evidence', enterpriseController.createRecoveryEvidence);
router.get('/security-policy', enterpriseController.getSecurityPolicy);
router.put('/security-policy', enterpriseController.updateSecurityPolicy);
router.get('/project-security', enterpriseController.listProjectSecurity);
router.put('/project-security/:id', enterpriseController.updateProjectSecurity);
router.get('/legal-holds', enterpriseController.listLegalHolds);
router.post('/legal-holds', enterpriseController.createLegalHold);
router.post('/legal-holds/:id/release', enterpriseController.releaseLegalHold);
router.get('/retention/preview', enterpriseController.retentionPreview);
router.get('/data-export', enterpriseController.exportOrganization);
router.get('/siem/destinations', enterpriseController.listSiemDestinations);
router.post('/siem/destinations', enterpriseController.createSiemDestination);
router.patch('/siem/destinations/:id/active', enterpriseController.setSiemDestinationActive);
router.post('/siem/destinations/:id/rotate-secret', enterpriseController.rotateSiemSecret);
router.get('/siem/deliveries', enterpriseController.listSiemDeliveries);
router.post('/siem/deliveries/:id/retry', enterpriseController.retrySiemDelivery);
router.get('/security-incidents', enterpriseController.listSecurityIncidents);
router.patch('/security-incidents/:id', enterpriseController.updateSecurityIncident);
router.get('/scim-tokens', enterpriseController.listScimTokens);
router.post('/scim-tokens', enterpriseController.createScimToken);
router.delete('/scim-tokens/:id', enterpriseController.revokeScimToken);
router.get('/oidc-providers', enterpriseController.listOidcProviders);
router.post('/oidc-providers', validate(createOidcProviderSchema), enterpriseController.createOidcProvider);
export default router;
