import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, AlertTriangle, CheckCircle2, DatabaseBackup, Save, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { operationalResilienceService, type OperationalPolicy } from '@/services/operational-resilience.service';
import { PageHeader } from '@/components/layout/PageChrome';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Skeleton } from '@/components/ui/skeleton';

const emptyEvidence = { type: 'BACKUP', status: 'SUCCESS', reference: '', checksum: '', measuredRpoMinutes: '', measuredRtoMinutes: '', notes: '' };

export default function OperationalReadinessPage() {
    const client = useQueryClient();
    const readiness = useQuery({ queryKey: ['operational-readiness'], queryFn: operationalResilienceService.readiness, refetchInterval: 30_000 });
    const policyQuery = useQuery({ queryKey: ['operational-policy'], queryFn: operationalResilienceService.getPolicy });
    const evidenceQuery = useQuery({ queryKey: ['recovery-evidence'], queryFn: operationalResilienceService.evidence });
    const [policyDraft, setPolicy] = useState<OperationalPolicy>();
    const [evidence, setEvidence] = useState(emptyEvidence);
    const policy = policyDraft || policyQuery.data;
    const refresh = () => { void client.invalidateQueries({ queryKey: ['operational-readiness'] }); void client.invalidateQueries({ queryKey: ['operational-policy'] }); void client.invalidateQueries({ queryKey: ['recovery-evidence'] }); };
    const savePolicy = useMutation({ mutationFn: () => operationalResilienceService.updatePolicy(policy!), onSuccess: (saved) => { setPolicy(saved); toast.success('Operasyon politikası kaydedildi'); refresh(); }, onError: (error: Error) => toast.error(error.message) });
    const saveEvidence = useMutation({ mutationFn: () => { const completedAt = new Date(); const startedAt = new Date(completedAt.getTime() - 60_000); return operationalResilienceService.createEvidence({ ...evidence, startedAt, completedAt, measuredRpoMinutes: evidence.measuredRpoMinutes ? Number(evidence.measuredRpoMinutes) : null, measuredRtoMinutes: evidence.measuredRtoMinutes ? Number(evidence.measuredRtoMinutes) : null }); }, onSuccess: () => { toast.success('Kurtarma kanıtı kaydedildi'); setEvidence(emptyEvidence); refresh(); }, onError: (error: Error) => toast.error(error.message) });
    if (readiness.isLoading || !policy) return <div className="page-shell"><Skeleton className="h-96" /></div>;
    const state = readiness.data;
    return <div className="page-shell page-stack"><PageHeader title={<span className="flex items-center gap-2"><Activity className="h-6 w-6 text-primary" />Operasyonel dayanıklılık</span>} description="SLO, hata bütçesi, altyapı readiness, RPO/RTO ve kurtarma kanıtlarını tek merkezden yönetin." />
        <div className="grid gap-3 md:grid-cols-4"><Metric label="Genel durum" value={state?.status === 'READY' ? 'Hazır' : 'Riskli'} ok={state?.status === 'READY'} /><Metric label="Kullanılabilirlik" value={state?.slo.availabilityPct == null ? 'Veri yok' : `%${state.slo.availabilityPct.toFixed(3)}`} ok={state?.slo.status === 'MEETING'} /><Metric label="P95 gecikme" value={state?.slo.latencyP95Ms == null ? 'Veri yok' : `${state.slo.latencyP95Ms} ms`} ok={state?.slo.status === 'MEETING'} /><Metric label="Hata bütçesi" value={state?.slo.status === 'NO_DATA' ? 'Veri yok' : `%${state?.slo.errorBudget.remainingPct.toFixed(1)} kaldı`} ok={!state?.slo.errorBudget.exhausted} /></div>
        {state?.blockers.length ? <Card className="border-destructive/40"><CardHeader><CardTitle className="flex items-center gap-2 text-destructive"><AlertTriangle className="h-5 w-5" />Canlıya çıkış engelleri</CardTitle></CardHeader><CardContent className="space-y-2">{state.blockers.map((item) => <div key={item} className="rounded-md bg-destructive/10 px-3 py-2 text-sm">{item}</div>)}</CardContent></Card> : <Card className="border-emerald-500/40"><CardContent className="flex items-center gap-3 p-5"><CheckCircle2 className="h-6 w-6 text-emerald-600" /><span className="font-medium">Tüm operasyonel kontroller geçildi.</span></CardContent></Card>}
        <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>SLO ve kurtarma politikası</CardTitle><CardDescription>Kurumun kabul ettiği hizmet ve felaket kurtarma hedefleri.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2">{([['availabilityTargetPct','Kullanılabilirlik (%)'],['latencyP95TargetMs','P95 gecikme (ms)'],['errorRateTargetPct','Azami hata oranı (%)'],['rpoTargetMinutes','RPO (dakika)'],['rtoTargetMinutes','RTO (dakika)'],['backupMaxAgeHours','Yedek azami yaşı (saat)']] as const).map(([key,label]) => <div className="space-y-2" key={key}><Label htmlFor={`policy-${key}`}>{label}</Label><Input id={`policy-${key}`} aria-label={label} type="number" value={policy[key]} onChange={(event) => setPolicy({ ...policy, [key]: Number(event.target.value) })} /></div>)}<div className="sm:col-span-2 rounded-lg border p-3"><Label className="flex items-center justify-between" htmlFor="maintenance-mode">Bakım modu<Switch id="maintenance-mode" aria-label="Bakım modu" checked={policy.maintenanceMode} onCheckedChange={(maintenanceMode) => setPolicy({ ...policy, maintenanceMode })} /></Label>{policy.maintenanceMode && <div className="mt-3 grid gap-3"><Input placeholder="Kullanıcılara gösterilecek bakım mesajı" value={policy.maintenanceMessage || ''} onChange={(event) => setPolicy({ ...policy, maintenanceMessage: event.target.value })} /><Input aria-label="Bakım bitiş zamanı" type="datetime-local" value={policy.maintenanceEndsAt?.slice(0,16) || ''} onChange={(event) => setPolicy({ ...policy, maintenanceEndsAt: event.target.value ? new Date(event.target.value).toISOString() : null })} /></div>}</div><div className="sm:col-span-2 flex justify-end"><Button data-testid="admin-readiness-save-policy-btn" onClick={() => savePolicy.mutate()} disabled={savePolicy.isPending}><Save className="mr-2 h-4 w-4" />Politikayı kaydet</Button></div></CardContent></Card>
        <Card><CardHeader><CardTitle>Kurtarma kanıtı ekle</CardTitle><CardDescription>Yedekleri checksum ile, tatbikatları ölçülen RPO/RTO ile kanıtlayın.</CardDescription></CardHeader><CardContent className="grid gap-3"><div className="grid grid-cols-2 gap-3"><Select value={evidence.type} onValueChange={(type) => setEvidence({ ...evidence, type })}><SelectTrigger aria-label="Kanıt tipi"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="BACKUP">Yedek</SelectItem><SelectItem value="RESTORE_DRILL">Geri yükleme tatbikatı</SelectItem></SelectContent></Select><Select value={evidence.status} onValueChange={(status) => setEvidence({ ...evidence, status })}><SelectTrigger aria-label="Kanıt durumu"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="SUCCESS">Başarılı</SelectItem><SelectItem value="FAILED">Başarısız</SelectItem></SelectContent></Select></div><Input placeholder="Kanıt / kasa / iş emri referansı" value={evidence.reference} onChange={(event) => setEvidence({ ...evidence, reference: event.target.value })} />{evidence.type === 'BACKUP' ? <Input placeholder="SHA-256 checksum (64 karakter)" value={evidence.checksum} onChange={(event) => setEvidence({ ...evidence, checksum: event.target.value })} /> : <div className="grid grid-cols-2 gap-3"><Input type="number" placeholder="Ölçülen RPO (dk)" value={evidence.measuredRpoMinutes} onChange={(event) => setEvidence({ ...evidence, measuredRpoMinutes: event.target.value })} /><Input type="number" placeholder="Ölçülen RTO (dk)" value={evidence.measuredRtoMinutes} onChange={(event) => setEvidence({ ...evidence, measuredRtoMinutes: event.target.value })} /></div>}<Textarea placeholder="Notlar" value={evidence.notes} onChange={(event) => setEvidence({ ...evidence, notes: event.target.value })} /><Button data-testid="admin-readiness-save-evidence-btn" onClick={() => saveEvidence.mutate()} disabled={saveEvidence.isPending || evidence.reference.trim().length < 3}><DatabaseBackup className="mr-2 h-4 w-4" />Kanıtı kaydet</Button></CardContent></Card></div>
        <Card><CardHeader><CardTitle>Altyapı kontrolleri ve kanıt geçmişi</CardTitle></CardHeader><CardContent><div className="mb-5 grid gap-2 sm:grid-cols-4">{Object.entries(state?.infrastructure.checks || {}).map(([name, check]) => <div key={name} className="rounded-lg border p-3"><div className="flex items-center justify-between"><span className="capitalize">{name}</span><Badge variant={check.healthy ? 'outline' : 'destructive'}>{check.healthy ? 'Sağlıklı' : 'Hatalı'}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{check.latencyMs} ms</p></div>)}</div><div className="space-y-2">{evidenceQuery.data?.map((item) => <div key={item.id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[140px_100px_1fr_auto]"><span>{item.type === 'BACKUP' ? 'Yedek' : 'Tatbikat'}</span><Badge variant={item.status === 'SUCCESS' ? 'outline' : 'destructive'}>{item.status === 'SUCCESS' ? 'Başarılı' : 'Başarısız'}</Badge><span className="truncate text-sm">{item.reference}</span><span className="text-xs text-muted-foreground">{new Date(item.completedAt).toLocaleString('tr-TR')}</span></div>)}{!evidenceQuery.data?.length && <p className="py-6 text-center text-sm text-muted-foreground">Henüz kurtarma kanıtı kaydedilmedi.</p>}</div></CardContent></Card>
    </div>;
}

function Metric({ label, value, ok }: { label: string; value: string; ok?: boolean }) { return <Card><CardContent className="flex items-center justify-between p-4"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold tabular-nums">{value}</p></div>{ok ? <ShieldCheck className="h-6 w-6 text-emerald-600" /> : <AlertTriangle className="h-6 w-6 text-amber-500" />}</CardContent></Card>; }
