import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, Copy, KeyRound, RefreshCw, RotateCcw, ShieldAlert, Webhook } from 'lucide-react';
import { toast } from 'sonner';
import { securityOperationsService, type SecurityIncident, type Severity } from '@/services/security-operations.service';
import { PageHeader } from '@/components/layout/PageChrome';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Skeleton } from '@/components/ui/skeleton';

const severityVariant = (severity: Severity) => severity === 'CRITICAL' || severity === 'HIGH' ? 'destructive' : severity === 'MEDIUM' ? 'secondary' : 'outline';

export default function SecurityOperationsPage() {
    const client = useQueryClient();
    const incidents = useQuery({ queryKey: ['security-incidents'], queryFn: securityOperationsService.listIncidents, refetchInterval: 30_000 });
    const destinations = useQuery({ queryKey: ['siem-destinations'], queryFn: securityOperationsService.listDestinations, refetchInterval: 30_000 });
    const deliveries = useQuery({ queryKey: ['siem-deliveries'], queryFn: securityOperationsService.listDeliveries, refetchInterval: 30_000 });
    const [destinationForm, setDestinationForm] = useState({ name: '', url: '', minimumSeverity: 'MEDIUM' as Severity, security: true, audit: false });
    const [shownSecret, setShownSecret] = useState<string>();
    const [incidentTarget, setIncidentTarget] = useState<SecurityIncident>();
    const [resolution, setResolution] = useState('');
    const invalidateSiem = () => { void client.invalidateQueries({ queryKey: ['siem-destinations'] }); void client.invalidateQueries({ queryKey: ['siem-deliveries'] }); };
    const createDestination = useMutation({ mutationFn: () => securityOperationsService.createDestination({ name: destinationForm.name, url: destinationForm.url, minimumSeverity: destinationForm.minimumSeverity, categories: [destinationForm.security && 'SECURITY', destinationForm.audit && 'AUDIT'].filter(Boolean) as string[] }), onSuccess: (result) => { setShownSecret(result.signingSecret); setDestinationForm({ name: '', url: '', minimumSeverity: 'MEDIUM', security: true, audit: false }); invalidateSiem(); }, onError: (error: Error) => toast.error(error.message || 'SIEM hedefi oluşturulamadı') });
    const toggleDestination = useMutation({ mutationFn: ({ id, isActive }: { id: string; isActive: boolean }) => securityOperationsService.setDestinationActive(id, isActive), onSuccess: invalidateSiem, onError: (error: Error) => toast.error(error.message) });
    const rotateSecret = useMutation({ mutationFn: securityOperationsService.rotateSecret, onSuccess: (result) => { setShownSecret(result.signingSecret); toast.success('İmzalama anahtarı yenilendi'); }, onError: (error: Error) => toast.error(error.message) });
    const retryDelivery = useMutation({ mutationFn: securityOperationsService.retryDelivery, onSuccess: () => { toast.success('Teslimat yeniden kuyruğa alındı'); invalidateSiem(); }, onError: (error: Error) => toast.error(error.message) });
    const updateIncident = useMutation({ mutationFn: ({ id, action, resolution }: { id: string; action: 'ACKNOWLEDGE' | 'RESOLVE' | 'REOPEN'; resolution?: string }) => securityOperationsService.updateIncident(id, { action, resolution }), onSuccess: () => { setIncidentTarget(undefined); setResolution(''); void client.invalidateQueries({ queryKey: ['security-incidents'] }); }, onError: (error: Error) => toast.error(error.message) });
    const openCount = incidents.data?.filter((incident) => incident.status !== 'RESOLVED').length || 0;
    const criticalCount = incidents.data?.filter((incident) => incident.status !== 'RESOLVED' && incident.severity === 'CRITICAL').length || 0;
    const deadCount = deliveries.data?.filter((delivery) => delivery.status === 'DEAD_LETTER').length || 0;

    return <div className="page-shell page-stack"><PageHeader title={<span className="flex items-center gap-2"><ShieldAlert className="h-6 w-6 text-primary" />Güvenlik operasyonları</span>} description="Güvenlik olaylarını yönetin ve imzalı SIEM teslimatlarının sağlığını izleyin." />
        <div className="grid gap-3 sm:grid-cols-3"><Summary label="Açık olay" value={openCount} critical={openCount > 0} /><Summary label="Kritik olay" value={criticalCount} critical={criticalCount > 0} /><Summary label="Dead-letter" value={deadCount} critical={deadCount > 0} /></div>
        <Tabs defaultValue="incidents"><TabsList><TabsTrigger data-testid="admin-security-ops-incidents-tab" value="incidents">Güvenlik olayları</TabsTrigger><TabsTrigger data-testid="admin-security-ops-destinations-tab" value="destinations">SIEM hedefleri</TabsTrigger><TabsTrigger data-testid="admin-security-ops-deliveries-tab" value="deliveries">Teslimatlar</TabsTrigger></TabsList>
            <TabsContent value="incidents" className="space-y-3">{incidents.isLoading ? <Skeleton className="h-64" /> : incidents.data?.length ? incidents.data.map((incident) => <Card key={incident.id}><CardContent className="flex flex-col gap-3 p-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge variant={severityVariant(incident.severity)}>{incident.severity}</Badge><Badge variant="outline">{incident.status}</Badge><span className="font-semibold">{incident.title}</span></div><p className="mt-2 text-sm text-muted-foreground">{incident.action} · {incident.entityType}/{incident.entityId}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(incident.createdAt).toLocaleString('tr-TR')} · IP: {incident.ip || '—'} · Hash: {incident.integrityHash?.slice(0, 16) || '—'}…</p>{incident.resolution && <p className="mt-2 text-sm">Çözüm: {incident.resolution}</p>}</div><div className="flex gap-2">{incident.status === 'OPEN' && <Button variant="outline" onClick={() => updateIncident.mutate({ id: incident.id, action: 'ACKNOWLEDGE' })}>Kabul et</Button>}{incident.status !== 'RESOLVED' ? <Button onClick={() => setIncidentTarget(incident)}>Çöz</Button> : <Button variant="outline" onClick={() => updateIncident.mutate({ id: incident.id, action: 'REOPEN' })}><RotateCcw className="mr-2 h-4 w-4" />Yeniden aç</Button>}</div></CardContent></Card>) : <Empty text="Güvenlik olayı bulunmuyor." />}</TabsContent>
            <TabsContent value="destinations" className="space-y-4"><Card><CardHeader><CardTitle>Yeni SIEM hedefi</CardTitle><CardDescription>Payload HMAC-SHA256 ile imzalanır. Anahtar yalnızca bir kez gösterilir.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><div className="space-y-2"><Label>Hedef adı</Label><Input value={destinationForm.name} onChange={(event) => setDestinationForm({ ...destinationForm, name: event.target.value })} placeholder="Kurumsal Splunk" /></div><div className="space-y-2"><Label>HTTPS webhook URL</Label><Input value={destinationForm.url} onChange={(event) => setDestinationForm({ ...destinationForm, url: event.target.value })} placeholder="https://siem.example.com/nexa" /></div><div className="space-y-2"><Label>Asgari önem</Label><Select value={destinationForm.minimumSeverity} onValueChange={(minimumSeverity: Severity) => setDestinationForm({ ...destinationForm, minimumSeverity })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{(['INFO','LOW','MEDIUM','HIGH','CRITICAL'] as Severity[]).map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><div className="flex items-center gap-5 rounded-lg border p-3"><Label className="flex items-center gap-2"><Switch checked={destinationForm.security} onCheckedChange={(security) => setDestinationForm({ ...destinationForm, security })} />Güvenlik</Label><Label className="flex items-center gap-2"><Switch checked={destinationForm.audit} onCheckedChange={(audit) => setDestinationForm({ ...destinationForm, audit })} />Tüm audit</Label></div><div className="md:col-span-2 flex justify-end"><Button data-testid="admin-security-ops-create-destination-btn" onClick={() => createDestination.mutate()} disabled={createDestination.isPending || destinationForm.name.trim().length < 3 || !destinationForm.url || (!destinationForm.security && !destinationForm.audit)}><Webhook className="mr-2 h-4 w-4" />Hedef oluştur</Button></div></CardContent></Card>
                {destinations.data?.map((destination) => <Card key={destination.id}><CardContent className="flex flex-col gap-3 p-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{destination.name}</span><Badge variant={destination.isActive ? 'outline' : 'secondary'}>{destination.isActive ? 'Etkin' : 'Devre dışı'}</Badge><Badge variant="outline">≥ {destination.minimumSeverity}</Badge></div><p className="mt-1 font-mono text-xs text-muted-foreground">{destination.url}</p><p className="mt-2 text-xs text-muted-foreground">{destination.deliveryCount} teslimat · {destination.pendingCount} bekleyen · {destination.deadLetterCount} dead-letter · Ardışık hata: {destination.consecutiveFailures}</p></div><div className="flex items-center gap-3"><Button variant="outline" size="sm" onClick={() => rotateSecret.mutate(destination.id)}><KeyRound className="mr-2 h-4 w-4" />Anahtarı yenile</Button><Switch checked={destination.isActive} onCheckedChange={(isActive) => toggleDestination.mutate({ id: destination.id, isActive })} /></div></CardContent></Card>)}
            </TabsContent>
            <TabsContent value="deliveries" className="space-y-2">{deliveries.data?.map((delivery) => <div key={delivery.id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[180px_120px_1fr_auto] md:items-center"><div><div className="font-medium">{delivery.destinationName}</div><div className="text-xs text-muted-foreground">{new Date(delivery.createdAt).toLocaleString('tr-TR')}</div></div><Badge variant={delivery.status === 'DEAD_LETTER' ? 'destructive' : delivery.status === 'DELIVERED' ? 'outline' : 'secondary'}>{delivery.status}</Badge><div className="text-sm"><div>{delivery.action}</div><div className="text-xs text-muted-foreground">{delivery.attempts} deneme · HTTP {delivery.responseCode || '—'} {delivery.lastError ? `· ${delivery.lastError}` : ''}</div></div>{delivery.status === 'DEAD_LETTER' && <Button size="sm" variant="outline" onClick={() => retryDelivery.mutate(delivery.id)}><RefreshCw className="mr-2 h-4 w-4" />Yeniden dene</Button>}</div>)}{!deliveries.data?.length && <Empty text="Henüz SIEM teslimatı yok." />}</TabsContent>
        </Tabs>
        <Dialog open={Boolean(shownSecret)} onOpenChange={(open) => { if (!open) setShownSecret(undefined); }}><DialogContent><DialogHeader><DialogTitle>SIEM imzalama anahtarı</DialogTitle><DialogDescription>Bu değer yeniden gösterilmez. SIEM tarafındaki doğrulama kasasına şimdi kaydedin.</DialogDescription></DialogHeader><div className="flex items-center gap-2 rounded-lg border bg-muted/40 p-3"><code className="min-w-0 flex-1 break-all text-xs">{shownSecret}</code><Button size="icon" variant="outline" aria-label="Anahtarı kopyala" title="Anahtarı kopyala" onClick={() => { void navigator.clipboard.writeText(shownSecret || ''); toast.success('Anahtar kopyalandı'); }}><Copy className="h-4 w-4" /></Button></div><DialogFooter><Button onClick={() => setShownSecret(undefined)}>Kaydettim</Button></DialogFooter></DialogContent></Dialog>
        <Dialog open={Boolean(incidentTarget)} onOpenChange={(open) => { if (!open) { setIncidentTarget(undefined); setResolution(''); } }}><DialogContent><DialogHeader><DialogTitle>Güvenlik olayını çöz</DialogTitle><DialogDescription>Yapılan incelemeyi, kanıtı ve alınan önlemi açıklayın.</DialogDescription></DialogHeader><Textarea value={resolution} onChange={(event) => setResolution(event.target.value)} placeholder="En az 10 karakterlik çözüm açıklaması" /><DialogFooter><Button variant="outline" onClick={() => setIncidentTarget(undefined)}>Vazgeç</Button><Button onClick={() => updateIncident.mutate({ id: incidentTarget!.id, action: 'RESOLVE', resolution })} disabled={resolution.trim().length < 10 || updateIncident.isPending}><CheckCircle2 className="mr-2 h-4 w-4" />Çözüldü olarak işaretle</Button></DialogFooter></DialogContent></Dialog>
    </div>;
}

function Summary({ label, value, critical }: { label: string; value: number; critical?: boolean }) { return <Card><CardContent className="flex items-center justify-between p-4"><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-bold tabular-nums">{value}</p></div>{critical ? <AlertTriangle className="h-6 w-6 text-destructive" /> : <CheckCircle2 className="h-6 w-6 text-emerald-600" />}</CardContent></Card>; }
function Empty({ text }: { text: string }) { return <Card><CardContent className="flex min-h-32 items-center justify-center text-sm text-muted-foreground">{text}</CardContent></Card>; }
